# Generated by Django 5.0.6 on 2024-06-22 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='Images/')),
                ('slogan', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('services', models.TextField(max_length=7000)),
            ],
        ),
        migrations.CreateModel(
            name='AddCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Images/')),
                ('description', models.TextField(max_length=2000)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('establishedYear', models.IntegerField()),
                ('authorisedDocuments', models.FileField(blank=True, upload_to='AuthorisedDocuments/')),
                ('statement', models.TextField(max_length=2000)),
                ('status', models.BooleanField(default=False)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='Images/')),
                ('description', models.TextField(max_length=2000)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('establishedYear', models.IntegerField()),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='Images/')),
                ('status', models.BooleanField(default=False)),
                ('charity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.charity')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donationDate', models.DateTimeField(auto_now_add=True)),
                ('paymentMethod', models.CharField(choices=[('Chapa', 'Chapa'), ('Telebirr', 'Telebirr'), ('CBE', 'CBE'), ('Other', 'Other')], max_length=50)),
                ('paymentTransactionID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('charity_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.charity')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.project')),
            ],
        ),
    ]
